on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: ğŸ”­ Checkout code
      uses: actions/checkout@v4

    - name: ğŸ« Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
        dune-cache: true

    - name: ğŸ“ Setup Coq
      run: |
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam pin add coq 8.20.0

    - name: ğŸ“ Setup Coq LSP
      run: opam install coq-lsp

    - name: ğŸŸ© Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: ğŸ—‚ï¸ Install dependencies
      run: npm install

    - name: ğŸƒğŸ»â€â¡ï¸ Test extension
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: ğŸƒğŸ»â€â¡ï¸ Test extension
      run: npm test
      if: runner.os != 'Linux'

    - name: ğŸƒğŸ»â€â¡ï¸ Test tmgrammar
      run: |
        npx vscode-tmgrammar-test -g ./src/syntax/syntaxes/coq-proof.json ./src/test/syntaxes/basic.test.v
        npx vscode-tmgrammar-test -g ./src/syntax/syntaxes/coq-proof.json ./src/test/syntaxes/advanced.test.v
        npx vscode-tmgrammar-test -g ./src/syntax/syntaxes/coq-proof.json ./src/test/syntaxes/comments.test.v

    
